name: .NET Core

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.300

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: pack Arity.Abstractions
      run: dotnet pack -o ./nupkg ./src/Arity.Abstractions/Arity.Abstractions.csproj

    - name: pack Arity
      run: dotnet pack -o ./nupkg ./src/Arity/Arity.csproj

    - name: pack Arity.DirectoryCatalog
      run: dotnet pack -o ./nupkg ./src/Arity.DirectoryCatalog/Arity.DirectoryCatalog.csproj

    - name: pack Arity.Hosting
      run: dotnet pack -o ./nupkg ./src/Arity.Hosting/Arity.Hosting.csproj

    - name: push Arity.Abstractions
      run: dotnet nuget push -k ${{ secrets.NUGET_KEY }} --skip-duplicate -s https://nuget.org ./nupkg/Arity.Abstractions.*.nupkg

    - name: push Arity
      run: dotnet nuget push -k ${{ secrets.NUGET_KEY }} --skip-duplicate -s https://nuget.org ./nupkg/Arity.*.nupkg

    - name: push Arity.DirectoryCatalog
      run: dotnet nuget push -k ${{ secrets.NUGET_KEY }} --skip-duplicate -s https://nuget.org ./nupkg/Arity.DirectoryCatalog.*.nupkg

    - name: push Arity.Hosting
      run: dotnet nuget push -k ${{ secrets.NUGET_KEY }} --skip-duplicate -s https://nuget.org ./nupkg/Arity.Hosting.*.nupkg
